name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      # Step 3: Sync your folder to S3 and make files public
      - name: Random Meal Generator
        run:  aws s3 sync "./001 - Random Meal Generator" s3://001-random-meal-generator --delete
      - name: Mood Calendar
        run: aws s3 sync "./002 - Mood Calendar" s3://002-mood-calendar --delete

      - name: Deploy Perlin Noise Flow Field
        run: |
          BUCKET=003-perlin-noise-flow-field
          # Create bucket if it doesn't exist
          aws s3api head-bucket --bucket $BUCKET 2>/dev/null || aws s3 mb s3://$BUCKET
          # Enable static website hosting
          aws s3 website s3://$BUCKET/ --index-document index.html --error-document error.html
          # Sync files and make them public individually
          aws s3 sync "./003 - Perlin Noise Flow Field" s3://$BUCKET --delete
